export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const SET_MINIMUM_STAKE = 'SET_MINIMUM_STAKE';
export const SET_MAXIMUM_STAKE = 'SET_MAXIMUM_STAKE';
